### ISSUE TITLE
Socket parsing from strace does not appear to capture all sockets

### ISSUE THREAD

**Issue by calebbrown** [ossf/package-analysis#324]
The strace parsing appears to be missing sockets.

For example: gs://ossf-malware-analysis-results/pypi/argpars/0.0.0.json

Clearly there is a `wget http://80.78.25....` but the IP address does not appear in the socket output.

**Comment by maxfisher-g** [comment]
Is there any way we can recover the argpars package in question to reproduce / debug this issue?

**Comment by maxfisher-g** [comment]
Found it, the link still seems to work for now - https://files.pythonhosted.org/packages/b8/0f/d78e840184b553c6e463e1d1c98cafd7119fa8bd8f0f47a724fe4aaa7de6/argpars-0.0.0.tar.gz

**Comment by maxfisher-g** [comment]
Okay after some investigation, it seems like the `wget` command was not running because the package tried to run it under `sudo` which was not installed. I modified the package to remove `sudo` and run `wget` on its own (and also add `--timeout=3 --tries=1` to prevent wget from retrying infinitely since the URL was no longer valid), and once I did so, the socket appeared in the strace output and the results json file.
